<x-portal.layouts.app :title="$application->name">
<a href="{{ route('portal.dashboard') }}" class="text-sm text-slate-500">&larr; Kembali</a>
<div class="mt-2 flex flex-wrap items-center gap-3"><h1 class="font-display text-2xl font-extrabold">{{ $application->name }}</h1><x-ui.badge :color="$application->application_status->badgeColor()">{{ $application->application_status->label() }}</x-ui.badge></div>
<p class="font-mono text-sm text-slate-500">{{ $application->registration_number }} &bull; {{ $application->program?->name }} &bull; {{ $application->period?->academic_year }}</p>

<ol class="mt-6 grid grid-cols-5 gap-1" aria-label="Tahapan PPDB">
@foreach($application->progressSteps() as $step)
<li><a href="{{ route('portal.applications.show', [$application, 'tahap' => $step['key']]) }}" class="block rounded-lg px-1 py-2 text-center text-[10px] font-semibold sm:text-xs {{ $stage === $step['key'] ? 'bg-primary-600 text-white' : 'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300' }}" @if($stage === $step['key']) aria-current="step" @endif><span class="mx-auto mb-1 flex size-5 items-center justify-center rounded-full {{ $step['state']==='done' ? 'bg-emerald-500 text-white' : ($step['state']==='attention' ? 'bg-red-500 text-white' : 'bg-white/20') }}">{{ $step['state']==='done' ? '✓' : $loop->iteration }}</span><span class="hidden sm:inline">{{ $step['label'] }}</span><span class="sm:hidden">{{ ['data'=>'Data','dokumen'=>'Dok.','verifikasi'=>'Verif.','wawancara'=>'Wawancara','hasil'=>'Hasil'][$step['key']] }}</span></a></li>
@endforeach
</ol>

@if($application->application_status->value==='needs_revision')<div class="mt-5"><x-ui.alert variant="danger" title="Perlu perbaikan">{{ $application->admin_notes }}</x-ui.alert></div>@endif

<div class="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1fr)_280px]"><div>
@if($stage === 'data')
<x-ui.card class="p-5 sm:p-6"><h2 class="font-bold">Data Pendaftaran</h2><dl class="mt-4 grid gap-4 sm:grid-cols-2"><div><dt class="text-xs uppercase text-slate-400">Nama</dt><dd class="font-semibold">{{ $application->name }}</dd></div><div><dt class="text-xs uppercase text-slate-400">NIK / NISN</dt><dd>{{ $application->nik ?: '—' }} / {{ $application->nisn ?: '—' }}</dd></div><div><dt class="text-xs uppercase text-slate-400">Tempat, tanggal lahir</dt><dd>{{ $application->birth_place ?: '—' }}, {{ $application->birth_date?->translatedFormat('d M Y') ?? '—' }}</dd></div><div><dt class="text-xs uppercase text-slate-400">Program</dt><dd>{{ $application->program?->name ?? '—' }}</dd></div><div class="sm:col-span-2"><dt class="text-xs uppercase text-slate-400">Alamat</dt><dd>{{ $application->address ?: '—' }}</dd></div></dl>@can('update', $application)<div class="mt-5"><x-ui.button href="{{ route('portal.applications.edit', $application) }}">Ubah Data Pendaftaran</x-ui.button></div>@endcan</x-ui.card>
@elseif($stage === 'dokumen')
<x-ui.card class="p-5 sm:p-6"><h2 class="font-bold">Dokumen</h2><p class="mt-1 text-sm text-slate-500">Pilih file untuk langsung mengunggah. Setiap kartu memiliki tujuan unggah yang terpisah.</p><ul class="mt-4 space-y-3">
@foreach($application->documents as $doc)
@php($canReplace = auth()->user()->can('uploadDocument', $application) && ($application->application_status->value === 'draft' || $doc->status->value === 'needs_revision'))
<li class="rounded-xl border p-3" data-document-card="{{ $doc->type->value }}"><div class="flex flex-wrap items-start justify-between gap-2"><div><p class="text-sm font-semibold">{{ $doc->type->label() }}</p><x-ui.badge :color="$doc->status->badgeColor()" size="sm"><span data-document-status>{{ $doc->status->label() }}</span></x-ui.badge>@if($doc->admin_note)<p class="mt-1 text-xs text-red-600">{{ $doc->admin_note }}</p>@endif</div>@if($doc->path)<a href="{{ route('portal.documents.preview', $doc) }}" target="_blank" class="text-sm font-semibold text-primary-700">Pratinjau</a>@endif</div>
@if($canReplace)<form method="POST" action="{{ route('portal.documents.upload', [$application, $doc->type->value]) }}" enctype="multipart/form-data" class="mt-3" data-document-upload novalidate>@csrf<x-ui.file-upload :id="'doc-upload-'.$doc->type->value" name="file" :accept="$doc->type->value === 'foto' ? 'JPG/PNG/WEBP' : 'JPG/PNG/WEBP/PDF'" :accept-attr="$doc->type->value === 'foto' ? 'image/jpeg,image/png,image/webp' : 'image/jpeg,image/png,image/webp,application/pdf'" :max-note="$doc->type->value === 'foto' ? 'Maks. 2 MB' : 'Maks. 4 MB'" button-text="{{ $doc->path ? 'Ganti ' . $doc->type->label() : 'Unggah ' . $doc->type->label() }}" :file-name="$doc->original_name" /><div class="mt-2 hidden h-1.5 overflow-hidden rounded-full bg-slate-200" data-upload-track><span class="block h-full bg-primary-600 transition-[width]" style="width:0" data-upload-progress></span></div><p class="mt-2 text-xs font-semibold text-slate-500" role="status" aria-live="polite" data-save-state>{{ $doc->path ? 'Terunggah' : 'Belum diunggah' }}</p></form>
@elseif($doc->path)<p class="mt-2 text-xs text-slate-500">Dokumen terkunci. Hubungi Admin PPDB resmi bila ada koreksi penting.</p>@endif</li>
@endforeach
</ul></x-ui.card>
@elseif($stage === 'verifikasi')
<x-ui.card class="p-6 text-center"><h2 class="font-bold">Verifikasi</h2>@if(in_array($application->application_status->value, ['submitted','resubmitted']))<p class="mt-2 text-sm text-slate-500">Pendaftaran telah dikirim dan sedang diperiksa oleh panitia.</p>@elseif($application->application_status->value === 'needs_revision')<p class="mt-2 text-sm text-slate-500">Perbaiki bagian yang ditandai, lalu kirim ulang melalui halaman review.</p><div class="mt-4"><x-ui.button href="{{ route('portal.applications.review', $application) }}">Review & Kirim Ulang</x-ui.button></div>@elseif($application->application_status->value === 'draft')<p class="mt-2 text-sm text-slate-500">Tinjau seluruh data dan dokumen sebelum pengiriman final.</p><div class="mt-4"><x-ui.button href="{{ route('portal.applications.review', $application) }}">Review & Kirim</x-ui.button></div>@else<p class="mt-2 text-sm font-semibold text-emerald-700">Pendaftaran telah diverifikasi.</p>@endif</x-ui.card>
@elseif($stage === 'wawancara')
<x-ui.card class="p-6"><h2 class="font-bold">Wawancara & Tahfizh/Tahsin</h2>@if($application->appointment)<p class="mt-2 text-sm">{{ $application->appointment->slot->date->translatedFormat('d M Y') }} pukul {{ $application->appointment->slot->start_time }} — {{ $application->appointment->slot->location ?? 'Lihat instruksi' }}</p><x-ui.badge :color="$application->appointment->status->badgeColor()" size="sm">{{ $application->appointment->status->label() }}</x-ui.badge>@elseif(in_array($application->application_status->value, ['verified','waiting_slot']))<p class="mt-2 text-sm text-slate-500">Pilih satu jadwal yang masih tersedia.</p><div class="mt-4"><x-ui.button href="{{ route('portal.slots.index', $application) }}">Pilih Jadwal Wawancara</x-ui.button></div>@else<p class="mt-2 text-sm text-slate-500">Tahap wawancara tersedia setelah verifikasi admin.</p>@endif</x-ui.card>
@else
<x-ui.card class="p-6 {{ $application->decision?->released_at && $application->decision->result->value==='passed' ? 'border-emerald-200 bg-emerald-50' : '' }}"><h2 class="font-bold">Hasil PPDB</h2>@if($application->decision?->released_at)<p class="mt-3 text-xl font-extrabold">{{ $application->decision->result->label() }}</p><p class="mt-2 text-sm leading-relaxed">{{ $application->decision->applicant_message ?: ($application->decision->result->value==='passed' ? 'Selamat! Anda dinyatakan lulus. Hubungi Admin PPDB resmi untuk administrasi lanjutan.' : 'Terima kasih telah mengikuti PPDB. Hubungi Admin PPDB resmi untuk informasi lebih lanjut.') }}</p>@else<p class="mt-2 text-sm text-slate-500">Hasil belum dirilis. Pantau portal dan notifikasi Anda.</p>@endif</x-ui.card>
@endif
</div><aside class="space-y-4"><x-ui.card class="p-5"><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Tindakan berikutnya</p><p class="mt-2 font-bold">{{ $nextAction['label'] }}</p>@if(!in_array($nextAction['label'], ['Menunggu Verifikasi','Menunggu Hasil']))<div class="mt-3"><x-ui.button size="sm" full="true" href="{{ $nextAction['route'] }}">{{ $nextAction['label'] }}</x-ui.button></div>@endif</x-ui.card>@if($application->isLockedForApplicant())<x-ui.card class="p-5"><h2 class="font-bold">Perlu koreksi data?</h2><p class="mt-2 text-sm text-slate-500">Data yang telah dikirim tidak dapat dibuka mandiri. Hubungi Admin PPDB resmi.</p>@if($application->period?->contact_info)<p class="mt-2 text-sm font-semibold">{{ $application->period->contact_info }}</p>@endif</x-ui.card>@endif<x-ui.card class="p-5"><h2 class="font-bold">Riwayat</h2><ul class="mt-2 space-y-2 text-xs text-slate-500">@foreach($application->history as $h)<li>{{ $h->created_at->format('d M Y H:i') }} — <strong>{{ str_replace('_',' ', $h->to_status) }}</strong></li>@endforeach</ul></x-ui.card></aside></div>

@push('scripts')
<script>
document.querySelectorAll('[data-document-upload]').forEach((form) => {
 const input=form.querySelector('input[type="file"]'),state=form.querySelector('[data-save-state]'),track=form.querySelector('[data-upload-track]'),bar=form.querySelector('[data-upload-progress]');
 input?.addEventListener('change',()=>{if(!input.files?.length)return;const payload=new FormData(form),xhr=new XMLHttpRequest();xhr.open('POST',form.action);xhr.setRequestHeader('Accept','application/json');state.textContent='Mengunggah…';state.className='mt-2 text-xs font-semibold text-amber-600';track.classList.remove('hidden');bar.style.width='0%';input.disabled=true;xhr.upload.addEventListener('progress',(e)=>{if(e.lengthComputable)bar.style.width=`${Math.round(e.loaded/e.total*100)}%`;});xhr.addEventListener('load',()=>{let body={};try{body=JSON.parse(xhr.responseText)}catch(_){}if(xhr.status>=200&&xhr.status<300){bar.style.width='100%';state.textContent='Terunggah';state.className='mt-2 text-xs font-semibold text-emerald-600';form.closest('[data-document-card]')?.querySelector('[data-document-status]')?.replaceChildren(document.createTextNode(body.document?.status||'Terunggah'));}else{state.textContent=body.message||Object.values(body.errors||{}).flat()[0]||'Unggahan gagal. Coba lagi.';state.className='mt-2 text-xs font-semibold text-red-600';input.value='';}input.disabled=false;});xhr.addEventListener('error',()=>{state.textContent='Koneksi terputus. File belum tersimpan.';state.className='mt-2 text-xs font-semibold text-red-600';input.disabled=false;input.value='';});xhr.send(payload);});
});
</script>
@endpush
</x-portal.layouts.app>
